using System;
using System.Collections.Generic;
using System.Text;

namespace Lazinator.Collections
{
    public enum LazinatorCollectionUniqueIDs
    {
        LazinatorOffsetList = 50, // leave room for built-in types
        LazinatorList,
        LazinatorFastReadList,
        WByte,
        WDouble,
        WFloat,
        WGuid,
        WInt,
        WLong,
        WNullableByte,
        WNullableChar,
        WNullableDateTime,
        WNullableDecimal,
        WNullableDouble,
        WNullableFloat,
        WNullableGuid,
        WNullableInt,
        WNullableLong,
        WNullableSByte,
        WNullableShort,
        LazinatorNullableTimeSpan,
        WNullableUint,
        WNullableUlong,
        WNullableUshort,
        WReadOnlySpanChar,
        WSByte,
        WShort,
        WString,
        WTimeSpan,
        WUint,
        WUlong,
        WUshort,
        WDateTime,
        WChar,
        WDecimal,
        WBool,
        WNullableBool,
        WAbstract,
        WrapperNullableStruct,
        ByteSpan,
        ByteSpanUnofficial,
        LazinatorBitArray,
        LazinatorBitArrayUnofficial,
        AvlNode,
        AvlTree,
        LazinatorTuple,
        AvlMultiset,
        AvlSet,
        DictionaryBucket,
        Dictionary,
        DictionaryUnofficial,
        WDecimalArray,
        WDoubleArray,
        WFloatArray,
        WIntArray,
        WLongArray,
        LazinatorTriple,
        LazinatorQueue,
        LazinatorStack,
        LazinatorArray,
        AvlList,
    }
}
