/*Location2136*//*Location2120*///8bf50f71-5f6f-d238-a31b-e3ff54a33bfc
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Lazinator tool, version 0.1.0.380
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable
namespace LazinatorTests.Examples.RemoteHierarchy
{/*Location2121*/
    using Lazinator.Attributes;/*Location2122*/
    using Lazinator.Buffers;/*Location2123*/
    using Lazinator.Core;/*Location2124*/
    using Lazinator.Exceptions;/*Location2125*/
    using Lazinator.Support;/*Location2126*/
    using Lazinator.Wrappers;/*Location2127*/
    using LazinatorCollections.Remote;/*Location2128*/
    using System;/*Location2129*/
    using System.Buffers;/*Location2130*/
    using System.Collections.Generic;/*Location2131*/
    using System.Diagnostics;/*Location2132*/
    using System.IO;/*Location2133*/
    using System.Linq;/*Location2134*/
    using System.Runtime.InteropServices;/*Location2135*/
    using static Lazinator.Core.LazinatorUtilities;
    
    [Autogenerated]
    public partial class RemoteHierarchy : ILazinator
    {
        /*Location2137*/public bool IsStruct => false;
        
        /*Location2138*//* Property definitions */
        
        /*Location2139*/        protected int _RemoteLevel1Item_ByteIndex;
        /*Location2140*/private int _RemoteHierarchy_EndByteIndex;
        /*Location2141*/protected virtual int _RemoteLevel1Item_ByteLength => _RemoteHierarchy_EndByteIndex - _RemoteLevel1Item_ByteIndex;
        
        /*Location2142*/
        protected int _TopOfHierarchyInt;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        public int TopOfHierarchyInt
        {
            get
            {
                return _TopOfHierarchyInt;
            }
            set
            {
                IsDirty = true;
                _TopOfHierarchyInt = value;
            }
        }
        /*Location2143*/
        protected Remote<WGuid, RemoteLevel1> _RemoteLevel1Item;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        public Remote<WGuid, RemoteLevel1> RemoteLevel1Item
        {
            get
            {
                if (!_RemoteLevel1Item_Accessed)
                {
                    Lazinate_RemoteLevel1Item();
                } 
                return _RemoteLevel1Item;
            }
            set
            {
                if (_RemoteLevel1Item != null)
                {
                    _RemoteLevel1Item.LazinatorParents = _RemoteLevel1Item.LazinatorParents.WithRemoved(this);
                }
                if (value != null)
                {
                    value.LazinatorParents = value.LazinatorParents.WithAdded(this);
                }
                
                IsDirty = true;
                DescendantIsDirty = true;
                _RemoteLevel1Item = value;
                _RemoteLevel1Item_Accessed = true;
            }
        }
        protected bool _RemoteLevel1Item_Accessed;
        private void Lazinate_RemoteLevel1Item()
        {
            if (LazinatorObjectBytes.Length == 0)
            {
                _RemoteLevel1Item = null;
            }
            else
            {
                LazinatorMemory childData = GetChildSlice(LazinatorMemoryStorage, _RemoteLevel1Item_ByteIndex, _RemoteLevel1Item_ByteLength, false, false, null);
                
                _RemoteLevel1Item = DeserializationFactory.Instance.CreateBaseOrDerivedType(254, (c, p) => new Remote<WGuid, RemoteLevel1>(c, p), childData, this); 
            }
            
            _RemoteLevel1Item_Accessed = true;
        }
        
        /*Location2146*/
        /* Serialization, deserialization, and object relationships */
        
        public RemoteHierarchy(LazinatorConstructorEnum constructorEnum)
        {
        }
        
        public RemoteHierarchy(LazinatorMemory serializedBytes, ILazinator parent = null)
        {
            LazinatorParents = new LazinatorParentsCollection(parent);
            DeserializeLazinator(serializedBytes);
            HasChanged = false;
            DescendantHasChanged = false;
        }
        
        public virtual LazinatorParentsCollection LazinatorParents { get; set; }
        
        public virtual IncludeChildrenMode OriginalIncludeChildrenMode { get; set; }
        
        public virtual int Deserialize()
        {
            FreeInMemoryObjects();
            int bytesSoFar = 0;
            ReadOnlySpan<byte> span = LazinatorObjectBytes.Span;
            if (span.Length == 0)
            {
                return 0;
            }
            
            ReadGenericIDIfApplicable(ContainsOpenGenericParameters, LazinatorUniqueID, span, ref bytesSoFar);
            
            int lazinatorLibraryVersion = span.ToDecompressedInt(ref bytesSoFar);
            
            int serializedVersionNumber = span.ToDecompressedInt(ref bytesSoFar);
            
            OriginalIncludeChildrenMode = (IncludeChildrenMode)span.ToByte(ref bytesSoFar);
            
            ConvertFromBytesAfterHeader(OriginalIncludeChildrenMode, serializedVersionNumber, ref bytesSoFar);
            return bytesSoFar;
        }
        
        public virtual LazinatorMemory SerializeLazinator(IncludeChildrenMode includeChildrenMode, bool verifyCleanness, bool updateStoredBuffer) 
        {
            if (LazinatorMemoryStorage.IsEmpty || includeChildrenMode != OriginalIncludeChildrenMode || (verifyCleanness || IsDirty || (includeChildrenMode != IncludeChildrenMode.ExcludeAllChildren && DescendantIsDirty)))
            {
                return EncodeToNewBuffer(includeChildrenMode, verifyCleanness, updateStoredBuffer);
            }
            BinaryBufferWriter writer = new BinaryBufferWriter(LazinatorMemoryStorage.Length);
            writer.Write(LazinatorMemoryStorage.Span);
            return writer.LazinatorMemory;
        }
        
        protected virtual LazinatorMemory EncodeToNewBuffer(IncludeChildrenMode includeChildrenMode, bool verifyCleanness, bool updateStoredBuffer) 
        {
            int bufferSize = LazinatorMemoryStorage.Length == 0 ? ExpandableBytes.DefaultMinBufferSize : LazinatorMemoryStorage.Length;
            BinaryBufferWriter writer = new BinaryBufferWriter(bufferSize);
            SerializeExistingBuffer(ref writer, includeChildrenMode, verifyCleanness, updateStoredBuffer);
            return writer.LazinatorMemory;
        }
        
        public virtual ILazinator CloneLazinator(IncludeChildrenMode includeChildrenMode = IncludeChildrenMode.IncludeAllChildren, CloneBufferOptions cloneBufferOptions = CloneBufferOptions.IndependentBuffers)
        {
            var clone = new RemoteHierarchy(LazinatorConstructorEnum.LazinatorConstructor)
            {
                OriginalIncludeChildrenMode = includeChildrenMode
            };
            clone = CompleteClone(this, clone, includeChildrenMode, cloneBufferOptions);
            return clone;
        }
        
        public virtual ILazinator AssignCloneProperties(ILazinator clone, IncludeChildrenMode includeChildrenMode)
        {
            clone.FreeInMemoryObjects();
            RemoteHierarchy typedClone = (RemoteHierarchy) clone;
            /*Location2144*/typedClone.TopOfHierarchyInt = TopOfHierarchyInt;
            /*Location2145*/if (includeChildrenMode != IncludeChildrenMode.ExcludeAllChildren && includeChildrenMode != IncludeChildrenMode.IncludeOnlyIncludableChildren)
            {
                if (RemoteLevel1Item == null)
                {
                    typedClone.RemoteLevel1Item = null;
                }
                else
                {
                    typedClone.RemoteLevel1Item = (Remote<WGuid, RemoteLevel1>) RemoteLevel1Item.CloneLazinator(includeChildrenMode, CloneBufferOptions.NoBuffer);
                }
                
            }
            
            
            return typedClone;
        }
        
        public virtual bool HasChanged { get; set; }
        
        protected bool _IsDirty;
        public virtual bool IsDirty
        {
            [DebuggerStepThrough]
            get => _IsDirty|| LazinatorObjectBytes.Length == 0;
            [DebuggerStepThrough]
            set
            {
                if (_IsDirty != value)
                {
                    _IsDirty = value;
                    if (_IsDirty)
                    {
                        LazinatorParents.InformParentsOfDirtiness();
                        HasChanged = true;
                    }
                }
            }
        }
        
        protected bool _DescendantHasChanged;
        public virtual bool DescendantHasChanged
        {
            [DebuggerStepThrough]
            get => _DescendantHasChanged;
            [DebuggerStepThrough]
            set
            {
                _DescendantHasChanged = value;
            }
        }
        
        protected bool _DescendantIsDirty;
        public virtual bool DescendantIsDirty
        {
            [DebuggerStepThrough]
            get => _DescendantIsDirty;
            [DebuggerStepThrough]
            set
            {
                if (_DescendantIsDirty != value)
                {
                    _DescendantIsDirty = value;
                    if (_DescendantIsDirty)
                    {
                        LazinatorParents.InformParentsOfDirtiness();
                        _DescendantHasChanged = true;
                    }
                }
            }
        }
        
        public virtual void DeserializeLazinator(LazinatorMemory serializedBytes)
        {
            LazinatorMemoryStorage = serializedBytes;
            int length = Deserialize();
            if (length != LazinatorMemoryStorage.Length)
            {
                LazinatorMemoryStorage = LazinatorMemoryStorage.Slice(0, length);
            }
        }
        
        public virtual LazinatorMemory LazinatorMemoryStorage
        {
            get;
            set;
        }
        protected virtual ReadOnlyMemory<byte> LazinatorObjectBytes => LazinatorMemoryStorage.IsEmpty ? LazinatorMemory.EmptyReadOnlyMemory : LazinatorMemoryStorage.Memory;
        
        public virtual void UpdateStoredBuffer()
        {
            if (!IsDirty && !DescendantIsDirty && LazinatorObjectBytes.Length > 0 && OriginalIncludeChildrenMode == IncludeChildrenMode.IncludeAllChildren)
            {
                return;
            }
            var previousBuffer = LazinatorMemoryStorage;
            if (LazinatorMemoryStorage.IsEmpty || IncludeChildrenMode.IncludeAllChildren != OriginalIncludeChildrenMode || (IsDirty || DescendantIsDirty))
            {
                LazinatorMemoryStorage = EncodeToNewBuffer(IncludeChildrenMode.IncludeAllChildren, false, true);
            }
            else
            {
                BinaryBufferWriter writer = new BinaryBufferWriter(LazinatorMemoryStorage.Length);
                writer.Write(LazinatorMemoryStorage.Span);
                LazinatorMemoryStorage = writer.LazinatorMemory;
            }
            OriginalIncludeChildrenMode = IncludeChildrenMode.IncludeAllChildren;
            if (!LazinatorParents.Any())
            {
                previousBuffer.Dispose();
            }
        }
        
        public virtual int GetByteLength()
        {
            UpdateStoredBuffer();
            return LazinatorObjectBytes.Length;
        }
        
        public virtual bool NonBinaryHash32 => false;
        
        /*Location2147*/
        public IEnumerable<ILazinator> EnumerateLazinatorNodes(Func<ILazinator, bool> matchCriterion, bool stopExploringBelowMatch, Func<ILazinator, bool> exploreCriterion, bool exploreOnlyDeserializedChildren, bool enumerateNulls)
        {
            bool match = (matchCriterion == null) ? true : matchCriterion(this);
            bool explore = (!match || !stopExploringBelowMatch) && ((exploreCriterion == null) ? true : exploreCriterion(this));
            if (match)
            {
                yield return this;
            }
            if (explore)
            {
                foreach (var item in EnumerateLazinatorDescendants(matchCriterion, stopExploringBelowMatch, exploreCriterion, exploreOnlyDeserializedChildren, enumerateNulls))
                {
                    yield return item.descendant;
                }
            }
        }
        
        /*Location2148*/public virtual IEnumerable<(string propertyName, ILazinator descendant)> EnumerateLazinatorDescendants(Func<ILazinator, bool> matchCriterion, bool stopExploringBelowMatch, Func<ILazinator, bool> exploreCriterion, bool exploreOnlyDeserializedChildren, bool enumerateNulls)
        {
            /*Location2149*/if (enumerateNulls && (!exploreOnlyDeserializedChildren || _RemoteLevel1Item_Accessed) && RemoteLevel1Item == null)
            {
                yield return ("RemoteLevel1Item", default);
            }
            else
            {
                if ((!exploreOnlyDeserializedChildren && RemoteLevel1Item != null) || (_RemoteLevel1Item_Accessed && _RemoteLevel1Item != null))
                {
                    bool isMatch_RemoteLevel1Item = matchCriterion == null || matchCriterion(RemoteLevel1Item);
                    bool shouldExplore_RemoteLevel1Item = exploreCriterion == null || exploreCriterion(RemoteLevel1Item);
                    if (isMatch_RemoteLevel1Item)
                    {
                        yield return ("RemoteLevel1Item", RemoteLevel1Item);
                    }
                    if ((!stopExploringBelowMatch || !isMatch_RemoteLevel1Item) && shouldExplore_RemoteLevel1Item)
                    {
                        foreach (var toYield in RemoteLevel1Item.EnumerateLazinatorDescendants(matchCriterion, stopExploringBelowMatch, exploreCriterion, exploreOnlyDeserializedChildren, enumerateNulls))
                        {
                            yield return ("RemoteLevel1Item" + "." + toYield.propertyName, toYield.descendant);
                        }
                    }
                }
                
            }
            
            /*Location2150*/yield break;
        }
        /*Location2151*/
        
        public virtual IEnumerable<(string propertyName, object descendant)> EnumerateNonLazinatorProperties()
        {
            /*Location2152*/yield return ("TopOfHierarchyInt", (object)TopOfHierarchyInt);
            /*Location2153*/yield break;
        }
        /*Location2154*/
        public virtual ILazinator ForEachLazinator(Func<ILazinator, ILazinator> changeFunc, bool exploreOnlyDeserializedChildren, bool changeThisLevel)
        {
            /*Location2155*/if ((!exploreOnlyDeserializedChildren && RemoteLevel1Item != null) || (_RemoteLevel1Item_Accessed && _RemoteLevel1Item != null))
            {
                _RemoteLevel1Item = (Remote<WGuid, RemoteLevel1>) _RemoteLevel1Item.ForEachLazinator(changeFunc, exploreOnlyDeserializedChildren, true);
            }
            /*Location2156*/if (changeThisLevel && changeFunc != null)
            {
                return changeFunc(this);
            }
            return this;
        }
        /*Location2157*/
        public virtual void FreeInMemoryObjects()
        {
            _RemoteLevel1Item = default;
            _RemoteLevel1Item_Accessed = false;
            IsDirty = false;
            DescendantIsDirty = false;
            HasChanged = false;
            DescendantHasChanged = false;
        }
        /*Location2158*/
        /* Conversion */
        
        public virtual int LazinatorUniqueID => 1082;
        
        protected virtual bool ContainsOpenGenericParameters => false;
        public virtual LazinatorGenericIDType LazinatorGenericID => default;
        
        
        public virtual int LazinatorObjectVersion { get; set; } = 0;
        
        
        /*Location2159*/public virtual void ConvertFromBytesAfterHeader(IncludeChildrenMode includeChildrenMode, int serializedVersionNumber, ref int bytesSoFar)
        {
            ReadOnlySpan<byte> span = LazinatorObjectBytes.Span;
            /*Location2160*/_TopOfHierarchyInt = span.ToDecompressedInt(ref bytesSoFar);
            /*Location2161*/_RemoteLevel1Item_ByteIndex = bytesSoFar;
            if (includeChildrenMode != IncludeChildrenMode.ExcludeAllChildren && includeChildrenMode != IncludeChildrenMode.IncludeOnlyIncludableChildren)
            {
                bytesSoFar = span.ToInt32(ref bytesSoFar) + bytesSoFar;
            }
            
            /*Location2162*/_RemoteHierarchy_EndByteIndex = bytesSoFar;
            /*Location2163*/        }
            
            /*Location2164*/public virtual void SerializeExistingBuffer(ref BinaryBufferWriter writer, IncludeChildrenMode includeChildrenMode, bool verifyCleanness, bool updateStoredBuffer)
            {
                /*Location2165*/if (includeChildrenMode != IncludeChildrenMode.IncludeAllChildren)
                {
                    updateStoredBuffer = false;
                }
                /*Location2166*/int startPosition = writer.Position;
                WritePropertiesIntoBuffer(ref writer, includeChildrenMode, verifyCleanness, updateStoredBuffer, true);
                /*Location2167*/if (updateStoredBuffer)
                {
                    UpdateStoredBuffer(ref writer, startPosition, writer.Position - startPosition, includeChildrenMode, false);
                    /*Location2168*/}
                    /*Location2169*/}
                    /*Location2170*/
                    public virtual void UpdateStoredBuffer(ref BinaryBufferWriter writer, int startPosition, int length, IncludeChildrenMode includeChildrenMode, bool updateDeserializedChildren)
                    {
                        /*Location2171*/_IsDirty = false;
                        if (includeChildrenMode == IncludeChildrenMode.IncludeAllChildren)
                        {
                            _DescendantIsDirty = false;/*Location2172*/
                            if (updateDeserializedChildren)
                            {
                                UpdateDeserializedChildren(ref writer, startPosition);
                                /*Location2173*/}
                                /*Location2174*//*Location2175*/
                            }
                            else
                            {
                                ThrowHelper.ThrowCannotUpdateStoredBuffer();
                            }
                            /*Location2176*/
                            var newBuffer = writer.Slice(startPosition, length);
                            LazinatorMemoryStorage = newBuffer;
                            /*Location2177*/}
                            /*Location2178*/
                            protected virtual void UpdateDeserializedChildren(ref BinaryBufferWriter writer, int startPosition)
                            {
                                /*Location2179*/if (_RemoteLevel1Item_Accessed && _RemoteLevel1Item != null)
                                {
                                    RemoteLevel1Item.UpdateStoredBuffer(ref writer, startPosition + _RemoteLevel1Item_ByteIndex + sizeof(int), _RemoteLevel1Item_ByteLength - sizeof(int), IncludeChildrenMode.IncludeAllChildren, true);
                                }
                                
                                /*Location2180*/}
                                
                                /*Location2181*/
                                protected virtual void WritePropertiesIntoBuffer(ref BinaryBufferWriter writer, IncludeChildrenMode includeChildrenMode, bool verifyCleanness, bool updateStoredBuffer, bool includeUniqueID)
                                {
                                    int startPosition = writer.Position;
                                    int startOfObjectPosition = 0;
                                    // header information
                                    /*Location2182*/if (includeUniqueID)
                                    {
                                        if (!ContainsOpenGenericParameters)
                                        {
                                            CompressedIntegralTypes.WriteCompressedInt(ref writer, LazinatorUniqueID);
                                        }
                                        else
                                        {
                                            WriteLazinatorGenericID(ref writer, LazinatorGenericID);
                                        }
                                    }
                                    /*Location2183*/CompressedIntegralTypes.WriteCompressedInt(ref writer, Lazinator.Support.LazinatorVersionInfo.LazinatorIntVersion);
                                    CompressedIntegralTypes.WriteCompressedInt(ref writer, LazinatorObjectVersion);
                                    writer.Write((byte)includeChildrenMode);
                                    /*Location2184*/// write properties
                                    /*Location2185*/CompressedIntegralTypes.WriteCompressedInt(ref writer, _TopOfHierarchyInt);
                                    /*Location2186*/startOfObjectPosition = writer.Position;
                                    /*Location2187*/if (includeChildrenMode != IncludeChildrenMode.ExcludeAllChildren && includeChildrenMode != IncludeChildrenMode.IncludeOnlyIncludableChildren)
                                    {
                                        if ((includeChildrenMode != IncludeChildrenMode.IncludeAllChildren || includeChildrenMode != OriginalIncludeChildrenMode) && !_RemoteLevel1Item_Accessed)
                                        {
                                            var deserialized = RemoteLevel1Item;
                                        }
                                        WriteChild(ref writer, ref _RemoteLevel1Item, includeChildrenMode, _RemoteLevel1Item_Accessed, () => GetChildSlice(LazinatorMemoryStorage, _RemoteLevel1Item_ByteIndex, _RemoteLevel1Item_ByteLength, false, false, null), verifyCleanness, updateStoredBuffer, false, false, this);
                                    }
                                    
                                    /*Location2188*/if (updateStoredBuffer)
                                    {
                                        _RemoteLevel1Item_ByteIndex = startOfObjectPosition - startPosition;
                                    }
                                    /*Location2189*/if (updateStoredBuffer)
                                    {
                                        /*Location2190*/_RemoteHierarchy_EndByteIndex = writer.Position - startPosition;
                                        /*Location2191*/}
                                        /*Location2192*/}
                                        /*Location2193*/
                                    }
                                }
