using System;
using System.Collections.Generic;
using System.Text;

namespace CountedTree
{
    public enum CountedTreeLazinatorUniqueIDs
    {
        KeyAndID = 800,
        RankAndID = 801,
        RankKeyAndID = 802,
        TreeInfo = 803,
        TreeStructure = 804,
        CountedNode = 805,
        CountedInternalNode = 806,
        CountedInternalNodeGeo = 807,
        CountedLeafNode = 808,
        CountedLeafNodeGeo = 809,
        CountedLeafNodeMatcher = 810,
        NodeInfo = 811,
        NodeBufferBaseMethods = 812,
        NodeBufferBase = 813,
        InternalNodeBuffer = 814,
        CumulativeBufferedChanges = 815,
        CombinedInternalNodeBuffer = 816,
        FurtherQueries = 817,
        NodeResultBase = 818,
        NodeResultGeoBase = 819,
        NodeResultGeoFilter = 820,
        NodeResultGeoFurtherQueries = 821,
        NodeResultGeoItems = 822,
        NodeResultIDs = 823,
        NodeResultKeys = 824,
        NodeResultKeysAndIDs = 825,
        NodeResultLinearBase = 826,
        NodeResultLinearFurtherQueries = 827,
        NodeResultRanksAndIDs = 828,
        NodeResultUintSet = 829,
        GeoResult = 830,
        NodeStorage = 831,
        InMemoryNodeStorage = 832,
        DelayedInMemoryNodeStorage = 833,
        BaseNodeStorage = 834,
        PendingChange = 835,
        PendingChangeEffect = 836,
        PendingChangesAtTime = 837,
        PendingChangesCollection = 838,
        PendingChangesOverTime = 839,
        PendingChangeStatus = 840,
        NodeQueryBase = 841,
        NodeQueryGeo = 842,
        NodeQueryIndexRange = 843,
        NodeQueryLinearBase = 844,
        NodeQueryValueRange = 845,
        QueryFilter = 846,
        UintSet = 847,
        UintSetDelta = 848,
        UintSetDeltas = 849,
        UintSetDeltasLoc = 850,
        UintSetDeltasWithLoc = 851,
        UintSetLoc = 852,
        UintSetWithLoc = 853,
        DeletionPlan = 854,
        NodeDeferralPlan = 855,
        NodeDeletionManager = 856,
        NodeDeletionStatus = 857,
        NodesDeletionPlan = 858,
        NodeToDelete = 859,
        NodeToDeleteLater = 860,
        TreeDeletionPlan = 861,
        CatchupPendingChangesTracker = 862,
        LastClientAccess = 863,
        RedundancyAvoider = 864,
        MoreResultsRequest = 865,
        TypeAheadItem = 866,
        TypeAheadItemsForParent = 867,
        TypeAheadNode = 868,
        HalfBytesStorage = 869,
        IncludedIndices = 870,
        ProperMortonRange = 871,
        LatLonPoint = 872,
        LatLonRectangle = 873,
        TreeHistoryManager = 874,
        TreeRebuilder = 875,
        RebuildSource = 876,
        InMemoryRebuildSource = 877,
        PlannedRebuildNode = 878,
        RebuildFromTreeSource = 879,
        TreeUpdateSettings = 880,
        CumulativeItemsCounter = 881,
        CombinedRebuildSource = 882,
        MultipleNodesReplacementResults = 883,
    }
}
